services:

  snake:
    image: ghcr.io/sean-mcguinness/m169-nginx-snake:v1
    container_name: snake
    ports:
      - "8081:8080"

  pong:
    image: ghcr.io/sean-mcguinness/m169-nginx-pong:v1
    container_name: pong
    ports:
      - "8082:8080"

  tictactoe:
    image: ghcr.io/sean-mcguinness/m169-nginx-tictactoe:v1
    container_name: tictactoe
    ports:
      - "8083:8080"