---
- name: Create IAM Role and S3 Bucket
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
    - community.aws
  vars_files:
    - creds_root.yml

  tasks:

    - name: S3Bucket erstellen
      amazon.aws.s3_bucket:
        name: modul346spielewebsite
        state: present
        region: us-east-1
        public_access: 
          block_public_acls : false
          block_public_policy: false
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        policy: |
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Sid": "PublicReadGetObject",
                      "Effect": "Allow",
                      "Principal": "*",
                      "Action": ["s3:GetObject"],
                      "Resource": ["arn:aws:s3:::modul346spielewebsite/*"]
                  }
              ]
          }        
        versioning: true

    - name: index.html Datei hochladen
      amazon.aws.s3_object:
        bucket: modul346spielewebsite
        object: index.html
        src: ./index.html
        mode: put
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"

    - name: S3 Bucket als Website konfigurieren
      community.aws.s3_website:
        name: modul346spielewebsite
        state: present
        suffix: index.html
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
